export const contentPages = [
  {
    key: 'about',
    path: '/about/',
    source: 'about/index.html',
    label: 'About',
    status: 'released',
    dependencies: ['partner'],
    primary: true,
  },
  {
    key: 'awards',
    path: '/awards/',
    source: 'awards/index.html',
    label: 'Awards',
    status: 'released',
    dependencies: [],
    primary: true,
  },
  {
    key: 'membership',
    path: '/membership/',
    source: 'membership/index.html',
    label: 'Membership',
    status: 'released',
    dependencies: [],
    primary: true,
  },
  {
    key: 'partner',
    path: '/become-a-partner/',
    source: 'become-a-partner/index.html',
    label: 'Partner',
    status: 'released',
    dependencies: ['ambassador'],
    footer: true,
  },
  {
    key: 'ambassador',
    path: '/become-a-brand-ambassador/',
    source: 'become-a-brand-ambassador/index.html',
    label: 'Ambassador',
    status: 'released',
    dependencies: [],
    footer: true,
  },
  {
    key: 'volunteer',
    path: '/become-a-volunteer/',
    source: 'become-a-volunteer/index.html',
    label: 'Volunteer',
    status: 'released',
    dependencies: [],
    footer: true,
  },
  {
    key: 'healthCheck',
    path: '/yogarise-marketing-health-check/',
    source: 'yogarise-marketing-health-check/index.html',
    label: 'Health Check',
    status: 'released',
    dependencies: [],
  },
  {
    key: 'expo',
    path: '/expo/',
    source: 'expo/index.html',
    label: 'Expo',
    status: 'released',
    dependencies: ['partner', 'ambassador'],
    primary: true,
  },
];

export function activeContentPages({ includeDrafts = false } = {}) {
  return contentPages.filter((page) => includeDrafts || page.status === 'released');
}
